name: lio_ui_example
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1
  google_fonts: ^6.1.0
  go_router: ^13.0.1
  flutter_hooks: ^0.20.4
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_gen_runner:
  build_runner: ^2.3.3


flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    
  fonts:
    enabled: true

  colors:
    enabled: true
    inputs: []


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

